// Hand-authored reference seed list (ISO 3166-1 country names/codes, UN
// M49-style region/subregion groupings) - real, standard, publicly
// documented reference data, not generated or invented. This is the
// "structure for 117-country support" buildCountryRegistry.mjs merges
// with whatever countries the app's actual research data currently
// covers - a country appearing here with no matching research record
// simply gets dataStatus: "no-data" (never a faked one).
//
// Source: standard ISO 3166-1 alpha-2/alpha-3 codes and UN geoscheme
// region/subregion names, the same reference classification used by
// REST Countries / Wikipedia's ISO 3166 tables.
export const COUNTRY_SEED_LIST = [
  { countryName: "Afghanistan", iso2: "AF", iso3: "AFG", region: "Asia", subregion: "Southern Asia" },
  { countryName: "Albania", iso2: "AL", iso3: "ALB", region: "Europe", subregion: "Southern Europe" },
  { countryName: "Algeria", iso2: "DZ", iso3: "DZA", region: "Africa", subregion: "Northern Africa" },
  { countryName: "Angola", iso2: "AO", iso3: "AGO", region: "Africa", subregion: "Middle Africa" },
  { countryName: "Argentina", iso2: "AR", iso3: "ARG", region: "Americas", subregion: "South America" },
  { countryName: "Armenia", iso2: "AM", iso3: "ARM", region: "Asia", subregion: "Western Asia" },
  { countryName: "Australia", iso2: "AU", iso3: "AUS", region: "Oceania", subregion: "Australia and New Zealand" },
  { countryName: "Austria", iso2: "AT", iso3: "AUT", region: "Europe", subregion: "Western Europe" },
  { countryName: "Azerbaijan", iso2: "AZ", iso3: "AZE", region: "Asia", subregion: "Western Asia" },
  { countryName: "Bahamas", iso2: "BS", iso3: "BHS", region: "Americas", subregion: "Caribbean" },
  { countryName: "Bahrain", iso2: "BH", iso3: "BHR", region: "Asia", subregion: "Western Asia" },
  { countryName: "Bangladesh", iso2: "BD", iso3: "BGD", region: "Asia", subregion: "Southern Asia" },
  { countryName: "Barbados", iso2: "BB", iso3: "BRB", region: "Americas", subregion: "Caribbean" },
  { countryName: "Belarus", iso2: "BY", iso3: "BLR", region: "Europe", subregion: "Eastern Europe" },
  { countryName: "Belgium", iso2: "BE", iso3: "BEL", region: "Europe", subregion: "Western Europe" },
  { countryName: "Belize", iso2: "BZ", iso3: "BLZ", region: "Americas", subregion: "Central America" },
  { countryName: "Benin", iso2: "BJ", iso3: "BEN", region: "Africa", subregion: "Western Africa" },
  { countryName: "Bhutan", iso2: "BT", iso3: "BTN", region: "Asia", subregion: "Southern Asia" },
  { countryName: "Bolivia", iso2: "BO", iso3: "BOL", region: "Americas", subregion: "South America" },
  { countryName: "Bosnia and Herzegovina", iso2: "BA", iso3: "BIH", region: "Europe", subregion: "Southern Europe" },
  { countryName: "Botswana", iso2: "BW", iso3: "BWA", region: "Africa", subregion: "Southern Africa" },
  { countryName: "Brazil", iso2: "BR", iso3: "BRA", region: "Americas", subregion: "South America" },
  { countryName: "Brunei", iso2: "BN", iso3: "BRN", region: "Asia", subregion: "South-eastern Asia" },
  { countryName: "Bulgaria", iso2: "BG", iso3: "BGR", region: "Europe", subregion: "Eastern Europe" },
  { countryName: "Burkina Faso", iso2: "BF", iso3: "BFA", region: "Africa", subregion: "Western Africa" },
  { countryName: "Burundi", iso2: "BI", iso3: "BDI", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Cambodia", iso2: "KH", iso3: "KHM", region: "Asia", subregion: "South-eastern Asia" },
  { countryName: "Cameroon", iso2: "CM", iso3: "CMR", region: "Africa", subregion: "Middle Africa" },
  { countryName: "Canada", iso2: "CA", iso3: "CAN", region: "Americas", subregion: "Northern America" },
  { countryName: "Cape Verde", iso2: "CV", iso3: "CPV", region: "Africa", subregion: "Western Africa" },
  { countryName: "Central African Republic", iso2: "CF", iso3: "CAF", region: "Africa", subregion: "Middle Africa" },
  { countryName: "Chad", iso2: "TD", iso3: "TCD", region: "Africa", subregion: "Middle Africa" },
  { countryName: "Chile", iso2: "CL", iso3: "CHL", region: "Americas", subregion: "South America" },
  { countryName: "China", iso2: "CN", iso3: "CHN", region: "Asia", subregion: "Eastern Asia" },
  { countryName: "Colombia", iso2: "CO", iso3: "COL", region: "Americas", subregion: "South America" },
  { countryName: "Comoros", iso2: "KM", iso3: "COM", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Costa Rica", iso2: "CR", iso3: "CRI", region: "Americas", subregion: "Central America" },
  { countryName: "Croatia", iso2: "HR", iso3: "HRV", region: "Europe", subregion: "Southern Europe" },
  { countryName: "Cuba", iso2: "CU", iso3: "CUB", region: "Americas", subregion: "Caribbean" },
  { countryName: "Cyprus", iso2: "CY", iso3: "CYP", region: "Asia", subregion: "Western Asia" },
  { countryName: "Czech Republic", iso2: "CZ", iso3: "CZE", region: "Europe", subregion: "Eastern Europe" },
  { countryName: "Democratic Republic of the Congo", iso2: "CD", iso3: "COD", region: "Africa", subregion: "Middle Africa" },
  { countryName: "Denmark", iso2: "DK", iso3: "DNK", region: "Europe", subregion: "Northern Europe" },
  { countryName: "Djibouti", iso2: "DJ", iso3: "DJI", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Dominican Republic", iso2: "DO", iso3: "DOM", region: "Americas", subregion: "Caribbean" },
  { countryName: "Ecuador", iso2: "EC", iso3: "ECU", region: "Americas", subregion: "South America" },
  { countryName: "Egypt", iso2: "EG", iso3: "EGY", region: "Africa", subregion: "Northern Africa" },
  { countryName: "El Salvador", iso2: "SV", iso3: "SLV", region: "Americas", subregion: "Central America" },
  { countryName: "Estonia", iso2: "EE", iso3: "EST", region: "Europe", subregion: "Northern Europe" },
  { countryName: "Ethiopia", iso2: "ET", iso3: "ETH", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Fiji", iso2: "FJ", iso3: "FJI", region: "Oceania", subregion: "Melanesia" },
  { countryName: "Finland", iso2: "FI", iso3: "FIN", region: "Europe", subregion: "Northern Europe" },
  { countryName: "France", iso2: "FR", iso3: "FRA", region: "Europe", subregion: "Western Europe" },
  { countryName: "Gabon", iso2: "GA", iso3: "GAB", region: "Africa", subregion: "Middle Africa" },
  { countryName: "Gambia", iso2: "GM", iso3: "GMB", region: "Africa", subregion: "Western Africa" },
  { countryName: "Georgia", iso2: "GE", iso3: "GEO", region: "Asia", subregion: "Western Asia" },
  { countryName: "Germany", iso2: "DE", iso3: "DEU", region: "Europe", subregion: "Western Europe" },
  { countryName: "Ghana", iso2: "GH", iso3: "GHA", region: "Africa", subregion: "Western Africa" },
  { countryName: "Greece", iso2: "GR", iso3: "GRC", region: "Europe", subregion: "Southern Europe" },
  { countryName: "Guatemala", iso2: "GT", iso3: "GTM", region: "Americas", subregion: "Central America" },
  { countryName: "Guinea", iso2: "GN", iso3: "GIN", region: "Africa", subregion: "Western Africa" },
  { countryName: "Guyana", iso2: "GY", iso3: "GUY", region: "Americas", subregion: "South America" },
  { countryName: "Haiti", iso2: "HT", iso3: "HTI", region: "Americas", subregion: "Caribbean" },
  { countryName: "Honduras", iso2: "HN", iso3: "HND", region: "Americas", subregion: "Central America" },
  { countryName: "Hungary", iso2: "HU", iso3: "HUN", region: "Europe", subregion: "Eastern Europe" },
  { countryName: "Iceland", iso2: "IS", iso3: "ISL", region: "Europe", subregion: "Northern Europe" },
  { countryName: "India", iso2: "IN", iso3: "IND", region: "Asia", subregion: "Southern Asia" },
  { countryName: "Indonesia", iso2: "ID", iso3: "IDN", region: "Asia", subregion: "South-eastern Asia" },
  { countryName: "Iran", iso2: "IR", iso3: "IRN", region: "Asia", subregion: "Southern Asia" },
  { countryName: "Iraq", iso2: "IQ", iso3: "IRQ", region: "Asia", subregion: "Western Asia" },
  { countryName: "Ireland", iso2: "IE", iso3: "IRL", region: "Europe", subregion: "Northern Europe" },
  { countryName: "Israel", iso2: "IL", iso3: "ISR", region: "Asia", subregion: "Western Asia" },
  { countryName: "Italy", iso2: "IT", iso3: "ITA", region: "Europe", subregion: "Southern Europe" },
  { countryName: "Ivory Coast", iso2: "CI", iso3: "CIV", region: "Africa", subregion: "Western Africa" },
  { countryName: "Jamaica", iso2: "JM", iso3: "JAM", region: "Americas", subregion: "Caribbean" },
  { countryName: "Japan", iso2: "JP", iso3: "JPN", region: "Asia", subregion: "Eastern Asia" },
  { countryName: "Jordan", iso2: "JO", iso3: "JOR", region: "Asia", subregion: "Western Asia" },
  { countryName: "Kazakhstan", iso2: "KZ", iso3: "KAZ", region: "Asia", subregion: "Central Asia" },
  { countryName: "Kenya", iso2: "KE", iso3: "KEN", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Kuwait", iso2: "KW", iso3: "KWT", region: "Asia", subregion: "Western Asia" },
  { countryName: "Kyrgyzstan", iso2: "KG", iso3: "KGZ", region: "Asia", subregion: "Central Asia" },
  { countryName: "Laos", iso2: "LA", iso3: "LAO", region: "Asia", subregion: "South-eastern Asia" },
  { countryName: "Latvia", iso2: "LV", iso3: "LVA", region: "Europe", subregion: "Northern Europe" },
  { countryName: "Lebanon", iso2: "LB", iso3: "LBN", region: "Asia", subregion: "Western Asia" },
  { countryName: "Lesotho", iso2: "LS", iso3: "LSO", region: "Africa", subregion: "Southern Africa" },
  { countryName: "Liberia", iso2: "LR", iso3: "LBR", region: "Africa", subregion: "Western Africa" },
  { countryName: "Libya", iso2: "LY", iso3: "LBY", region: "Africa", subregion: "Northern Africa" },
  { countryName: "Lithuania", iso2: "LT", iso3: "LTU", region: "Europe", subregion: "Northern Europe" },
  { countryName: "Luxembourg", iso2: "LU", iso3: "LUX", region: "Europe", subregion: "Western Europe" },
  { countryName: "Madagascar", iso2: "MG", iso3: "MDG", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Malawi", iso2: "MW", iso3: "MWI", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Malaysia", iso2: "MY", iso3: "MYS", region: "Asia", subregion: "South-eastern Asia" },
  { countryName: "Maldives", iso2: "MV", iso3: "MDV", region: "Asia", subregion: "Southern Asia" },
  { countryName: "Mali", iso2: "ML", iso3: "MLI", region: "Africa", subregion: "Western Africa" },
  { countryName: "Malta", iso2: "MT", iso3: "MLT", region: "Europe", subregion: "Southern Europe" },
  { countryName: "Mauritania", iso2: "MR", iso3: "MRT", region: "Africa", subregion: "Western Africa" },
  { countryName: "Mauritius", iso2: "MU", iso3: "MUS", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Mexico", iso2: "MX", iso3: "MEX", region: "Americas", subregion: "Central America" },
  { countryName: "Moldova", iso2: "MD", iso3: "MDA", region: "Europe", subregion: "Eastern Europe" },
  { countryName: "Monaco", iso2: "MC", iso3: "MCO", region: "Europe", subregion: "Western Europe" },
  { countryName: "Mongolia", iso2: "MN", iso3: "MNG", region: "Asia", subregion: "Eastern Asia" },
  { countryName: "Montenegro", iso2: "ME", iso3: "MNE", region: "Europe", subregion: "Southern Europe" },
  { countryName: "Morocco", iso2: "MA", iso3: "MAR", region: "Africa", subregion: "Northern Africa" },
  { countryName: "Mozambique", iso2: "MZ", iso3: "MOZ", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Myanmar", iso2: "MM", iso3: "MMR", region: "Asia", subregion: "South-eastern Asia" },
  { countryName: "Namibia", iso2: "NA", iso3: "NAM", region: "Africa", subregion: "Southern Africa" },
  { countryName: "Nepal", iso2: "NP", iso3: "NPL", region: "Asia", subregion: "Southern Asia" },
  { countryName: "Netherlands", iso2: "NL", iso3: "NLD", region: "Europe", subregion: "Western Europe" },
  { countryName: "New Zealand", iso2: "NZ", iso3: "NZL", region: "Oceania", subregion: "Australia and New Zealand" },
  { countryName: "Nicaragua", iso2: "NI", iso3: "NIC", region: "Americas", subregion: "Central America" },
  { countryName: "Niger", iso2: "NE", iso3: "NER", region: "Africa", subregion: "Western Africa" },
  { countryName: "Nigeria", iso2: "NG", iso3: "NGA", region: "Africa", subregion: "Western Africa" },
  { countryName: "North Korea", iso2: "KP", iso3: "PRK", region: "Asia", subregion: "Eastern Asia" },
  { countryName: "North Macedonia", iso2: "MK", iso3: "MKD", region: "Europe", subregion: "Southern Europe" },
  { countryName: "Norway", iso2: "NO", iso3: "NOR", region: "Europe", subregion: "Northern Europe" },
  { countryName: "Oman", iso2: "OM", iso3: "OMN", region: "Asia", subregion: "Western Asia" },
  { countryName: "Pakistan", iso2: "PK", iso3: "PAK", region: "Asia", subregion: "Southern Asia" },
  { countryName: "Panama", iso2: "PA", iso3: "PAN", region: "Americas", subregion: "Central America" },
  { countryName: "Papua New Guinea", iso2: "PG", iso3: "PNG", region: "Oceania", subregion: "Melanesia" },
  { countryName: "Paraguay", iso2: "PY", iso3: "PRY", region: "Americas", subregion: "South America" },
  { countryName: "Peru", iso2: "PE", iso3: "PER", region: "Americas", subregion: "South America" },
  { countryName: "Philippines", iso2: "PH", iso3: "PHL", region: "Asia", subregion: "South-eastern Asia" },
  { countryName: "Poland", iso2: "PL", iso3: "POL", region: "Europe", subregion: "Eastern Europe" },
  { countryName: "Portugal", iso2: "PT", iso3: "PRT", region: "Europe", subregion: "Southern Europe" },
  { countryName: "Qatar", iso2: "QA", iso3: "QAT", region: "Asia", subregion: "Western Asia" },
  { countryName: "Republic of the Congo", iso2: "CG", iso3: "COG", region: "Africa", subregion: "Middle Africa" },
  { countryName: "Romania", iso2: "RO", iso3: "ROU", region: "Europe", subregion: "Eastern Europe" },
  { countryName: "Russia", iso2: "RU", iso3: "RUS", region: "Europe", subregion: "Eastern Europe" },
  { countryName: "Rwanda", iso2: "RW", iso3: "RWA", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Saudi Arabia", iso2: "SA", iso3: "SAU", region: "Asia", subregion: "Western Asia" },
  { countryName: "Senegal", iso2: "SN", iso3: "SEN", region: "Africa", subregion: "Western Africa" },
  { countryName: "Serbia", iso2: "RS", iso3: "SRB", region: "Europe", subregion: "Southern Europe" },
  { countryName: "Seychelles", iso2: "SC", iso3: "SYC", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Sierra Leone", iso2: "SL", iso3: "SLE", region: "Africa", subregion: "Western Africa" },
  { countryName: "Singapore", iso2: "SG", iso3: "SGP", region: "Asia", subregion: "South-eastern Asia" },
  { countryName: "Slovakia", iso2: "SK", iso3: "SVK", region: "Europe", subregion: "Eastern Europe" },
  { countryName: "Slovenia", iso2: "SI", iso3: "SVN", region: "Europe", subregion: "Southern Europe" },
  { countryName: "Solomon Islands", iso2: "SB", iso3: "SLB", region: "Oceania", subregion: "Melanesia" },
  { countryName: "Somalia", iso2: "SO", iso3: "SOM", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "South Africa", iso2: "ZA", iso3: "ZAF", region: "Africa", subregion: "Southern Africa" },
  { countryName: "South Korea", iso2: "KR", iso3: "KOR", region: "Asia", subregion: "Eastern Asia" },
  { countryName: "South Sudan", iso2: "SS", iso3: "SSD", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Spain", iso2: "ES", iso3: "ESP", region: "Europe", subregion: "Southern Europe" },
  { countryName: "Sri Lanka", iso2: "LK", iso3: "LKA", region: "Asia", subregion: "Southern Asia" },
  { countryName: "Sudan", iso2: "SD", iso3: "SDN", region: "Africa", subregion: "Northern Africa" },
  { countryName: "Suriname", iso2: "SR", iso3: "SUR", region: "Americas", subregion: "South America" },
  { countryName: "Sweden", iso2: "SE", iso3: "SWE", region: "Europe", subregion: "Northern Europe" },
  { countryName: "Switzerland", iso2: "CH", iso3: "CHE", region: "Europe", subregion: "Western Europe" },
  { countryName: "Syria", iso2: "SY", iso3: "SYR", region: "Asia", subregion: "Western Asia" },
  { countryName: "Taiwan", iso2: "TW", iso3: "TWN", region: "Asia", subregion: "Eastern Asia" },
  { countryName: "Tajikistan", iso2: "TJ", iso3: "TJK", region: "Asia", subregion: "Central Asia" },
  { countryName: "Tanzania", iso2: "TZ", iso3: "TZA", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Thailand", iso2: "TH", iso3: "THA", region: "Asia", subregion: "South-eastern Asia" },
  { countryName: "Togo", iso2: "TG", iso3: "TGO", region: "Africa", subregion: "Western Africa" },
  { countryName: "Trinidad and Tobago", iso2: "TT", iso3: "TTO", region: "Americas", subregion: "Caribbean" },
  { countryName: "Tunisia", iso2: "TN", iso3: "TUN", region: "Africa", subregion: "Northern Africa" },
  { countryName: "Turkey", iso2: "TR", iso3: "TUR", region: "Asia", subregion: "Western Asia" },
  { countryName: "Turkmenistan", iso2: "TM", iso3: "TKM", region: "Asia", subregion: "Central Asia" },
  { countryName: "Uganda", iso2: "UG", iso3: "UGA", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Ukraine", iso2: "UA", iso3: "UKR", region: "Europe", subregion: "Eastern Europe" },
  { countryName: "United Arab Emirates", iso2: "AE", iso3: "ARE", region: "Asia", subregion: "Western Asia" },
  { countryName: "United Kingdom", iso2: "GB", iso3: "GBR", region: "Europe", subregion: "Northern Europe" },
  { countryName: "United States", iso2: "US", iso3: "USA", region: "Americas", subregion: "Northern America" },
  { countryName: "Uruguay", iso2: "UY", iso3: "URY", region: "Americas", subregion: "South America" },
  { countryName: "Uzbekistan", iso2: "UZ", iso3: "UZB", region: "Asia", subregion: "Central Asia" },
  { countryName: "Vanuatu", iso2: "VU", iso3: "VUT", region: "Oceania", subregion: "Melanesia" },
  { countryName: "Venezuela", iso2: "VE", iso3: "VEN", region: "Americas", subregion: "South America" },
  { countryName: "Vietnam", iso2: "VN", iso3: "VNM", region: "Asia", subregion: "South-eastern Asia" },
  { countryName: "Yemen", iso2: "YE", iso3: "YEM", region: "Asia", subregion: "Western Asia" },
  { countryName: "Zambia", iso2: "ZM", iso3: "ZMB", region: "Africa", subregion: "Eastern Africa" },
  { countryName: "Zimbabwe", iso2: "ZW", iso3: "ZWE", region: "Africa", subregion: "Eastern Africa" },
];
