// Global research source registry (Phase 1 of the global research scanner -
// see docs/GLOBAL_RESEARCH_SOURCE_STRATEGY.md). A real, hand-authored
// catalog of the EXTERNAL DATA PROVIDERS the discovery pipeline is allowed
// to query/fetch from - distinct from src/data/sourceRegistry.js, which
// documents provenance metadata for records ALREADY extracted, not which
// providers exist and how they may be accessed. Every entry here is a
// real, documented, publicly-known source; nothing here is invented, and
// no source is marked `enabled: true` unless this app's ingestion code
// already knows how to (or safely could) call it without violating the
// no-AI-fetching / no-scraping-of-blocked-domains rules in CLAUDE.md.

export const GLOBAL_SOURCE_REGISTRY = [
  {
    sourceId: "openalex",
    sourceName: "OpenAlex",
    sourceType: "structured-api",
    baseUrl: "https://api.openalex.org",
    officialDocsUrl: "https://docs.openalex.org",
    accessType: "public-api",
    requiresApiKey: false,
    requiresLicense: false,
    rateLimitNotes: "Polite pool via mailto param; generous shared rate limit, no key needed.",
    dataTypes: ["publications", "authorships", "institutions", "concepts"],
    credibilityTier: "high",
    credibilityReason: "Open, structured metadata index maintained by OurResearch; already the primary source for this app's real extracted records.",
    enabled: true,
  },
  {
    sourceId: "crossref",
    sourceName: "Crossref",
    sourceType: "structured-api",
    baseUrl: "https://api.crossref.org",
    officialDocsUrl: "https://www.crossref.org/documentation/retrieve-metadata/rest-api/",
    accessType: "public-api",
    requiresApiKey: false,
    requiresLicense: false,
    rateLimitNotes: "Polite pool via mailto param; used today to verify DOIs on OpenAlex-derived records.",
    dataTypes: ["publications", "doi-metadata"],
    credibilityTier: "high",
    credibilityReason: "Official DOI registration agency - authoritative for publication metadata.",
    enabled: true,
  },
  {
    sourceId: "cordis",
    sourceName: "CORDIS (EU Research Results)",
    sourceType: "official-project-database",
    baseUrl: "https://cordis.europa.eu",
    officialDocsUrl: "https://cordis.europa.eu/about/en",
    accessType: "public-website",
    requiresApiKey: false,
    requiresLicense: false,
    rateLimitNotes: "No public bulk API used here - project pages are fetched individually and politely (see discoverOfficialSources.mjs).",
    dataTypes: ["funded-projects", "consortium-info", "budget"],
    credibilityTier: "high",
    credibilityReason: "Official European Commission database of EU-funded research projects.",
    enabled: true,
  },
  {
    sourceId: "openaire",
    sourceName: "OpenAIRE",
    sourceType: "structured-api",
    baseUrl: "https://api.openaire.eu",
    officialDocsUrl: "https://graph.openaire.eu/docs/apis/graph-api/",
    accessType: "public-api",
    requiresApiKey: false,
    requiresLicense: false,
    rateLimitNotes: "Real REST API confirmed working with an explicit Accept: application/xml header; the human explore.openaire.eu UI sits behind a bot-detection interstitial and is never scraped (see discoverOfficialSources.mjs).",
    dataTypes: ["funded-projects", "publications"],
    credibilityTier: "high",
    credibilityReason: "EU-funded open science infrastructure aggregating funder/project metadata.",
    enabled: true,
  },
  {
    sourceId: "ror",
    sourceName: "ROR (Research Organization Registry)",
    sourceType: "structured-api",
    baseUrl: "https://api.ror.org",
    officialDocsUrl: "https://ror.readme.io/",
    accessType: "public-api",
    requiresApiKey: false,
    requiresLicense: false,
    rateLimitNotes: "Not yet called by this pipeline (parked for a lean MVP, see CLAUDE.md) - listed here as a known-safe future source for institution identity resolution.",
    dataTypes: ["institution-identifiers"],
    credibilityTier: "high",
    credibilityReason: "Community-governed open registry of research organization identifiers.",
    enabled: false,
  },
  {
    sourceId: "government-funding-page",
    sourceName: "Government / funding-body pages (generic category)",
    sourceType: "official-government-page",
    baseUrl: null,
    officialDocsUrl: null,
    accessType: "public-website",
    requiresApiKey: false,
    requiresLicense: false,
    rateLimitNotes: "Fetched individually and politely, one page per record - no bulk crawling.",
    dataTypes: ["programme-pages", "press-releases"],
    credibilityTier: "high",
    credibilityReason: "Official .gov/.europa.eu/national-authority domains - matches scripts/processing/imageSourceClassifier.mjs's government/funding keyword check.",
    enabled: true,
    exampleUrls: ["https://www.mpa.gov.sg/maritime-singapore/innovation-and-r-d"],
  },
  {
    sourceId: "university-project-page",
    sourceName: "University / institution project pages (generic category)",
    sourceType: "official-institution-page",
    baseUrl: null,
    officialDocsUrl: null,
    accessType: "public-website",
    requiresApiKey: false,
    requiresLicense: false,
    rateLimitNotes: "Fetched individually and politely - one or two pages per institution, never a full-site crawl.",
    dataTypes: ["project-pages", "about-pages", "campus-images"],
    credibilityTier: "medium",
    credibilityReason: "Official .edu/.ac.xx domains are a strong but not certain signal (some serve repository/journal content, not project pages - see REPOSITORY_OR_ARTICLE_PATH_PATTERN in imageSourceClassifier.mjs).",
    enabled: true,
  },
  {
    sourceId: "wikimedia-commons",
    sourceName: "Wikimedia Commons",
    sourceType: "media-repository",
    baseUrl: "https://commons.wikimedia.org",
    officialDocsUrl: "https://commons.wikimedia.org/wiki/Commons:Licensing",
    accessType: "public-website",
    requiresApiKey: false,
    requiresLicense: false,
    rateLimitNotes: "Image-only source; only used when license/attribution metadata is present alongside the file.",
    dataTypes: ["images"],
    credibilityTier: "medium",
    credibilityReason: "Community-curated media repository - real license metadata per file, but not an official institution page itself.",
    enabled: true,
  },
  {
    sourceId: "wikipedia-wikidata",
    sourceName: "Wikipedia / Wikidata",
    sourceType: "discovery-only",
    baseUrl: "https://www.wikidata.org",
    officialDocsUrl: "https://www.wikidata.org/wiki/Wikidata:Introduction",
    accessType: "public-website",
    requiresApiKey: false,
    requiresLicense: false,
    rateLimitNotes: "Discovery-only, per Foundation Step spec - never treated as a final image/data source unless it points to Wikimedia Commons with license metadata.",
    dataTypes: ["discovery-links"],
    credibilityTier: "low",
    credibilityReason: "Crowd-edited encyclopedia - useful for finding an institution's real official domain, never authoritative on its own.",
    enabled: true,
  },
  {
    sourceId: "doi-resolver",
    sourceName: "doi.org (DOI resolver)",
    sourceType: "redirect-only",
    baseUrl: "https://doi.org",
    officialDocsUrl: "https://www.doi.org/",
    accessType: "restricted",
    requiresApiKey: false,
    requiresLicense: false,
    rateLimitNotes: "Never fetched directly for content - it redirects to the publisher's page, which is usually paywalled/blocked anyway (see classifyImageSourceUrl's doi_redirect category).",
    dataTypes: ["redirect"],
    credibilityTier: "low",
    credibilityReason: "A redirect layer, not a content source - real identifier, but nothing to extract from the resolver itself.",
    enabled: false,
  },
  {
    sourceId: "academic-publisher",
    sourceName: "Academic publisher article pages (generic category: MDPI/Elsevier/Springer/Wiley/IEEE/etc.)",
    sourceType: "paywalled-publisher",
    baseUrl: null,
    officialDocsUrl: null,
    accessType: "license-required",
    requiresApiKey: false,
    requiresLicense: true,
    rateLimitNotes: "Never fetched for content - frequently blocks automated requests and requires a subscription/license for full text; metadata only comes via OpenAlex/Crossref instead.",
    dataTypes: ["full-text (blocked)"],
    credibilityTier: "medium",
    credibilityReason: "The underlying research is credible (peer-reviewed), but the PAGE ITSELF is not a safely fetchable source - see PUBLISHER_HOSTNAMES in imageSourceClassifier.mjs.",
    enabled: false,
  },
  {
    sourceId: "stock-photo-site",
    sourceName: "Stock photo sites (generic category: Shutterstock/iStock/Getty/etc.)",
    sourceType: "stock-media",
    baseUrl: null,
    officialDocsUrl: null,
    accessType: "restricted",
    requiresApiKey: false,
    requiresLicense: true,
    rateLimitNotes: "Never a legitimate research or institution-image source - listed here only so the credibility classifier has a real, named reject case to test against.",
    dataTypes: [],
    credibilityTier: "low",
    credibilityReason: "Generic commercial imagery, never institution- or record-specific.",
    enabled: false,
  },
];

export function getSourceById(sourceId) {
  return GLOBAL_SOURCE_REGISTRY.find((s) => s.sourceId === sourceId) ?? null;
}

export function getEnabledSources() {
  return GLOBAL_SOURCE_REGISTRY.filter((s) => s.enabled);
}
