/**
 * Manually curated maritime R&D records.
 *
 * This is a fifth data source alongside OpenAlex/Crossref/ROR/MPA — for
 * real projects a human found and verified themselves (a real institution
 * page, a real news article, etc.) rather than something an automated
 * query surfaced. It exists because:
 *
 *   - AI must never fetch/scrape webpages to populate this file (see
 *     CLAUDE.md architecture rule 1) — a human reads the source and
 *     writes the summary in their own words below.
 *   - Every entry still needs a real source URL and a real date, same as
 *     every other record in this app (CLAUDE.md rule 3).
 *   - This file only needs editing when you add/update a project by hand
 *     — it is not regenerated by `npm run sync:data`.
 *
 * Required fields per entry:
 *   title              string   Project/paper/programme name
 *   countryCode        string   2-letter ISO code — must exist in
 *                                scripts/ingestion/config.mjs COUNTRY_ATLAS_NAMES
 *   leadOrganisation   string   Institution, company, or government body
 *   summary            string   1-3 sentences, YOUR OWN WORDS, based on
 *                                what you actually read at sourceUrl —
 *                                do not paste large blocks of the source
 *   categories         string[] Pick from the list in
 *                                src/data/researchProjectData.js
 *                                topicToProjectCategories (values), e.g.
 *                                "Autonomous navigation", "Vessel efficiency",
 *                                "Maritime cybersecurity" — anything outside
 *                                that list won't link to a topic page.
 *   sourceUrl          string   The exact page you read (http/https)
 *   sourceName         string   Publisher/site/organisation name
 *   sourceDate         string   "YYYY-MM-DD" — when you found/verified this
 *
 * Optional fields: city, partnerOrganisations[], technologies[],
 * projectStatus, startDate, authorityLevel ("A" government/official,
 * "B" university/institution — default, "C" publication, "D" company
 * announcement, "E" specialist news).
 */

export const manualSources = [
  // Example (remove the leading `//` markers to activate):
  // {
  //   title: "Example Autonomous Ferry Trial",
  //   countryCode: "SG",
  //   leadOrganisation: "Example Maritime Institute",
  //   summary:
  //     "A pilot trial of an autonomous passenger ferry on a fixed inner-harbour route, reported by the institute in mid-2026.",
  //   categories: ["Autonomous navigation"],
  //   sourceUrl: "https://example.org/autonomous-ferry-trial",
  //   sourceName: "Example Maritime Institute",
  //   sourceDate: "2026-06-01",
  // },
];
